.PHONY: clean All

All:
	@echo "----------Building project:[ Grafos - Debug ]----------"
	@cd "Grafos" && "$(MAKE)" -f  "Grafos.mk"
clean:
	@echo "----------Cleaning project:[ Grafos - Debug ]----------"
	@cd "Grafos" && "$(MAKE)" -f  "Grafos.mk" clean
